# using the master branch of StatsMods
# and term2.0 branch of MixedModels

# d_lmer.rds generated by exporting d_lmer from the paper Rmd
# d_lmer %>% select(log_lt, trial_type, method, trial_num, age_mo, trial_type, nae, subid, item, lab)
# note that only relevant columns are exported so that dropmissing!() doesn't drop too much

using MixedModels, RData, DataFrames

d_lmer = categorical!(load("d_lmer.rds"), [:item, :lab, :subid]);
d_lmer = dropmissing!(d_lmer);
describe(d_lmer)

lmm = LinearMixedModel;

mod0 = fit!(lmm(@formula(log_lt ~ 1 + trial_type * method +
                   trial_type * trial_num +
                   age_mo * trial_num +
                   trial_type * age_mo * nae +
                   (1 + trial_type| subid) +
                   (1 | item) + 
                   (1 + trial_type | lab)),d_lmer), verbose=true)

mod1 = fit!(lmm(@formula(log_lt ~ 1 + trial_type * method * trial_num * age_mo * nae +
                   (1 + trial_type| subid) +
                   (1 | item) + 
                   (1 + trial_type | lab)),d_lmer), verbose=true)
                   
                   mod1 = fit!(lmm(@formula(log_lt ~ 1 + trial_type * method * trial_num * age_mo * nae +
                   (1 + trial_type| subid) +
                   (1 | item) + 
                   (1 + trial_type | lab)),d_lmer), verbose=true)
                   
mod2 = fit!(lmm(@formula(log_lt ~ 1 + trial_type * method * trial_num * age_mo * nae +
                   (1 + trial_type + method * trial_num + age_mo + nae| subid) +
                   (1 | item) + 
                   (1 + trial_type + method * trial_num + age_mo + nae | lab)),d_lmer), verbose=true)